name: Clear Vercel Check Runs
on:
  push:
    branches:
      - main # Adjust to your default branch
jobs:
  clear-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clear Vercel checks
        uses: actions/github-script@v6
        with:
          script: |
            const checks = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            for (const check of checks.data.check_runs) {
              if (check.name.includes("Vercel")) {
                await github.rest.checks.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  check_run_id: check.id,
                  status: "completed",
                  conclusion: "cancelled"
                });
              }
            }
